# Generated by Django 5.2 on 2025-04-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(db_column='ID_producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('descripcion', models.TextField(db_column='Descripcion')),
                ('precio_compra_cu', models.DecimalField(db_column='Precio_compra_CU', decimal_places=2, max_digits=10)),
                ('precio_venta_cu', models.DecimalField(db_column='Precio_venta_CU', decimal_places=2, max_digits=10)),
                ('ganancia', models.DecimalField(db_column='Ganancia', decimal_places=2, max_digits=10)),
                ('marca', models.CharField(db_column='Marca', max_length=50)),
                ('categoria', models.CharField(db_column='Categoria', max_length=50)),
                ('stock', models.IntegerField(db_column='Stock')),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
    ]
